title: Benjamin Yolken
subtitle: Adventures in software engineering
email: benjamin@yolken.net
description: >-
  Random thoughts from the perspective of a software engineer, particularly around
  tech careers and development processes.
baseurl: ""
url: "https://yolken.net"
github_username: yolken
show_excerpts: true
permalink: /blog/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
